### ISSUE TITLE
可否添加针对全志H6的内核预编译文件？

### ISSUE THREAD

**Issue by 13584452567** [ophub/kernel#12]
最近在适配泰奇猫的时候发现全志使用的硬件有很多并不符合规范的地方。为适配所打的补丁可能会对其它设备产生负面影响。

在这个仓库添加内核文件之后可否将其作为armbian仓库的H6芯片的默认内核？

**Comment by ophub** [comment]
https://github.com/ophub/kernel

- 在 [pub/stable](https://github.com/ophub/kernel/blob/main/pub/stable) 目录下存储的内核文件是稳定版，适合在正式生产环境中使用。
- 在 [pub/rk3588](https://github.com/ophub/kernel/blob/main/pub/rk3588) 目录下存储的内核文件是 rk3588 系列的专用版本，适合 Rock-5B 和 HinLink-H88K 等设备，和其他系列不通用。
- 在 [pub/dev](https://github.com/ophub/kernel/blob/main/pub/dev) 目录下存储的内核文件是开发版，为一些特定盒子添加了第三方的驱动支持和特殊修改，供开发和测试使用。

目前rk3588就不同于别的设备，使用的独立内核，如果全志不能和别的通用，可以添加独立内核目录。

**Comment by 13584452567** [comment]
为什么我使用aml-s9xx-armbian仓库的actions编译出来的boot-*.tar.gz文件内没有vmlinux和system.map文件呢？

等5.10能够稳定编译之后我会尝试patch并维护6.1.y分支。

这是目前的5.10.y源码仓库：https://github.com/13584452567/linux-5.10.y

**Comment by ophub** [comment]
build是yes，我看了下是因为每次选择的是5.15和6.1内核，所以这个没有匹配到5.10的被忽略了。我先手动编译一个，我想想给他做个特殊处理以后自动加入编译列表。

**Comment by ophub** [comment]
你的源码有错误，编译会中断，所以没生成那3个文件。

**Comment by 13584452567** [comment]
> 你的源码有错误，编译会中断，所以没生成那3个文件。

yes,it`s my fault.

this is the new repo link:https://github.com/13584452567/linux-6.1.y

**Comment by ophub** [comment]
这个可以正常编译，泰奇猫之前说只能使用5.10的内核，可以使用6.1了？

**Comment by 13584452567** [comment]
> 这个可以正常编译，泰奇猫之前说只能使用5.10的内核，可以使用6.1了？

之前是这样的，现在我正在往6.1内核上面打补丁。测试目前这个内核已经能够正常启动了，emmc,无线正常。蓝牙需要提交固件，有线网补丁已经打上去了暂未测试。

刚才arch更新把输入法更炸了

**Comment by ophub** [comment]
蓝牙的固件可以放这里：https://github.com/ophub/firmware
compile-kernel.yml内核编译在Actions的kernel_source里添加一个来源即可：13584452567

https://github.com/ophub/amlogic-s9xxx-armbian/blob/cea150aab82150a6fb7dd3ba7c85587c3a1d26b3/.github/workflows/compile-kernel.yml#L18

**Comment by ophub** [comment]
内核仓库里，这个目录名叫什么呢，叫h6吧？

**Comment by 13584452567** [comment]
嗯，叫H6就行

**Comment by ophub** [comment]
6.1.y中午还能编译，现在又报错了。

**Comment by 13584452567** [comment]
> 6.1.y中午还能编译，现在又报错了。

我的仓库看起来编译成功了。https://github.com/13584452567/amlogic-s9xxx-armbian/releases/tag/kernel_6.1.18

**Comment by ophub** [comment]
armbian和openwrt的打包仓库都升级完成了，我打包了下可以正常工作，你试试最新的固件。
以后内核你有制作的最新版本就推送到这个仓库里。有什么调整的新内核随时推送更新即可。

**Comment by 13584452567** [comment]
6.4和6.5都更新了

**Comment by ophub** [comment]
早上看见你昨天半夜更新了，我早上已经编好了
