### ISSUE TITLE
增加设备驱动内核模块

### ISSUE THREAD

**Issue by shom** [ophub/kernel#17]
能否增加xr_serial模块，RX21V1410 串口转 USB需要这个

**Comment by ophub** [comment]
https://github.com/ophub/kernel/commit/2c88f24a8d0d1a2e4a7a9c35950e9106c5112b90

开启了，重新编译一下5.15的内核。
6.1的内核已经是启用状态。
这个选项在5.12.y以后的内核才添加的，所以5.4和5.10不可用。

**Comment by shom** [comment]
> 

好的
