### ISSUE TITLE
kernel_flippy

### ISSUE THREAD

**Issue by esaaprillia** [ophub/kernel#19]
Plis update kernel_flippy

**Comment by ophub** [comment]
Already the latest version

**Comment by esaaprillia** [comment]
Thanks

**Comment by esaaprillia** [comment]
@ophub 

i build in imagebuilder and choose flippy kernel but kernel download stable kernel. this looks like a bug

![Screenshot_2023-04-25_212408](https://user-images.githubusercontent.com/122262432/234292227-cddcbaec-3bf2-447c-9113-26913b0c5dc8.jpg)

**Comment by ophub** [comment]
https://github.com/esaaprillia/amlogic-s9xxx-openwrt/blob/d3417e3b5557876bbe399a1c56333de90e4a2b9f/make#L89

dont’t change script

**Comment by esaaprillia** [comment]
> https://github.com/esaaprillia/amlogic-s9xxx-openwrt/blob/d3417e3b5557876bbe399a1c56333de90e4a2b9f/make#L89
> 
> do not change script keep `kernel_default="stable"`

I've tried not changing kernel_default="stable" but the result is the same

**Comment by ophub** [comment]
Run Actions again

**Comment by esaaprillia** [comment]
@ophub 

must download ```kernel_flippy``` not ```kernel_stable``` if choose ```flippy``` problem still persist. I have tried the first time you added the flippy kernel everything worked fine. it breaks when you make changes

![Screenshot_2023-04-26_103302](https://user-images.githubusercontent.com/122262432/234454690-7a4a230e-dad7-489a-aae1-d93fd50ef42c.jpg)
![Screenshot_2023-04-26_104422](https://user-images.githubusercontent.com/122262432/234454728-a5e1ff27-ec78-45d7-8fad-0c3ec5905d08.jpg)

**Comment by esaaprillia** [comment]
@ophub 

thank you if you have fixed. can you add ```rootfs_size``` in this imagebuilder also remove it while making changes

**Comment by ophub** [comment]
Imagebuilder does not have this setting.
The tar file does not have a size method

**Comment by esaaprillia** [comment]
> Imagebuilder does not have this setting. The tar file does not have a size method

https://github.com/ophub/amlogic-s9xxx-openwrt/blob/47e8227de985057bbe178bf92826b736af43421a/action.yml#L34
