### ISSUE TITLE
RK3328-L1Pro 換了新核心後風扇就不轉

### ISSUE THREAD

**Issue by sillydanny** [ophub/kernel#22]
**Device Information | 设备信息**
 - SOC: [RK3328]
 - Model [L1-Pro]

**System Version | 系统版本**
 - System: [Armbian]

**Kernel Version | 内核版本**
 - Kernel Version: [5.15.120]

**Describe the bug | 问题描述**

RK3328-L1Pro 換了新核心後風扇就不轉了，只會開機時初始化一下。
嘗試不同的Kernel 
- Kernel_flippy 的5.15.120, 
- Kernel_statle的6.1.34和6.1.38

請問OPHUB大佬, 有沒有一個腳本可以控制l1pro的風扇?

Please provide a detailed description of the issue and, if necessary, attach a screenshot.

溫度長期在66-73之間，好像在高溫情況下, SMB性能會減弱。

![2023-07-12_113626](https://github.com/ophub/kernel/assets/22260040/93dc5a1d-35ba-44ac-a8e9-79d9d8b3cfc1)

![2023-07-12_113838](https://github.com/ophub/kernel/assets/22260040/9d668b32-d0e0-448e-baff-a6c819fc692c)

**Comment by ophub** [comment]
你之前风扇可以转时使用的是哪个内核版本？

**Comment by sillydanny** [comment]
> 你之前风扇可以转时使用的是哪个内核版本？

我之前是刷這固件`Armbian_20.10_L1-Pro_buster_5.10.26-flippy-56+.img.xz` 固件 (好早期Flippy制作的固件,下載於Flippy電報群組), 最後用大佬你提供的腳本升級kernel. 在這裡也一併感謝.

**Comment by ophub** [comment]
更新内核时，会自动备份原来的内核至：/ddbr/backup，你可以恢复

**Comment by sillydanny** [comment]
謝謝, ophub大佬，請問我提取原來的5.10.26 kernel給你, 可以應用到新的內核嗎?

**Comment by ophub** [comment]
你使用之前的旧版内核即可，暂时不要更新现在的版本了。我前几天在群里也看到有个人反应说现在的内核风扇不转的问题，我不了解内核，不知道这是在哪个内核选项里设置。

**Comment by sillydanny** [comment]
> 你使用之前的旧版内核即可，暂时不要更新现在的版本了。我前几天在群里也看到有个人反应说现在的内核风扇不转的问题，我不了解内核，不知道这是在哪个内核选项里设置。

Ok, 等你更新修復這個問題，謝謝。

**Comment by Erick23629** [comment]
1
