### ISSUE TITLE
解析固件失败

### ISSUE THREAD

**Issue by thiesymon** [ophub/kernel#28]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model：UNT402A

**System Version | 系统版本**
 - System: [e.g. Armbian/OpenWrt]

**Kernel Version | 内核版本**
 - Kernel Version: [e.g. 5.15.100]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

使用aml_burning_toolV3.2.0导入Armbian_24.2.0_amlogic_s905l3_jammy_6.1.66_server_2023.12.08.img解析固件失败
也使用了v2.6导入也是解析固件失败 如何解决呢？
![image](https://github.com/ophub/kernel/assets/49362220/7c43606d-2ec1-4327-8a5e-d8aa7c105a04)

**Comment by ophub** [comment]
安卓刷机工具不能线刷armbian, 使用方法看文档
