### ISSUE TITLE
测试6.6.21、22内核不支持TVI3315A的无线

### ISSUE THREAD

**Issue by tramplong** [ophub/kernel#29]
**Device Information | 设备信息**
 - SOC: [rk3399]
 - Model [TVI3315a]

**System Version | F大最新的rootfs
 - System: [OpenWrt]

**Kernel Version | 6.6.21/22
 - Kernel Version: [ 6.6.21/22]

**Describe the bug | 问题描述**
最新的6.6.x内核不支持TVI3315A的无线，同样的rootfs用6.1.81/82均无问题

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
什么无线芯片

**Comment by tramplong** [comment]
AP6255

**Comment by zhanglei-1987** [comment]
这个板6.6.30也不支持
