### ISSUE TITLE
Header scripts binaries are x86-64 binaries 

### ISSUE THREAD

**Issue by lepz0r** [ophub/kernel#6]
Because of this we can't build kernel modules

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/20bd9a271b3fc0cb9e4a3b083061be51e3153241/recompile#L321-L350

I checked the kernel compilation script, the binaries are ARM64

**Comment by lepz0r** [comment]
but on Armbian some of it is x86_64

```
armbian:basic:% pwd
/usr/src/linux-headers-5.10.156-ophub/scripts/basic
armbian:basic:% binwalk fixdep

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             ELF, 64-bit LSB shared object, AMD x86-64, version 1 (SYSV)

armbian:basic:% 
```

**Comment by ophub** [comment]
![Snip20221127_1](https://user-images.githubusercontent.com/68696949/204119069-de58ca0e-6375-4486-8ee0-645f869b9327.png)

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/dev

armbian-update -v dev -k 6.1.12
