### ISSUE TITLE
Q: Why do you remove old kernels?

### ISSUE THREAD

**Issue by bulezas** [ophub/kernel#9]
Q: Why do you remove old kernels?

**Comment by ophub** [comment]
. git files larger than 2G will not be easy to manage. 

It is a habit to use the latest version. When there is a new version, few people will see that there are new ones and use the old ones. 

It is also a habit not to waste the free space of github.

**Comment by bulezas** [comment]
Why not just use releases? Older kernels can be very important sometimes.

**Comment by ophub** [comment]
I also delete releases every week and clean them regularly. I also wrote a delete action to do this job.

https://github.com/ophub/delete-releases-workflows

It is unreasonable to occupy 100% of the resources and effort for 1% of the possible people.

If you like a historical version, you can save it yourself.
